import os


class Config:
    SECRET_KEY = os.environ['FLASK_SECRET_KEY']
    SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    HYDRA_CLIENT_ID = os.environ['HYDRA_CLIENT_ID']
    HYDRA_CLIENT_SECRET = os.environ['HYDRA_CLIENT_SECRET']
    HYDRA_PUBLIC_URL = os.environ['HYDRA_PUBLIC_URL']
